AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/bundle/**/*'
    - 'Gemfile'
    - 'lib/tasks/cucumber.rake'
    - 'features/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 130

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Documentation:
    Enabled: false

NumericLiterals:
  MinDigits: 11

Style/TrailingBlankLines:
  Enabled: false

Style/BlockComments:
  Enabled: false

Rails/TimeZone:
  Enabled: false